### ISSUE TITLE
Can't spawn frida-trace on targets that have flags or arguments

### ISSUE THREAD

**Issue by jnwilson** [nowsecure/frida-trace#27]
I can frida-trace programs that don't have argument, but, I want to trace a program that must take non-trivial arguments.
Consider this example. When I try to

   frida-trace --decorate -i \*read* /bin/ls -la

I get this result:

   usage: frida-trace [options] target
   frida-trace: error: unrecognized arguments: -la

I thought about trying to start the program in the background, immediately suspend it, let frida-trace figure out the handlers, etc., but frida-trace won't attach to a stopped process.

Is there any thought to allowing the args following the target to be passed to the target instead of eaten by frida?
Or is there some other way to achieve my goal?

(BTW, I can't escape the arguments with \, because there is no corresponding unescape in the program I want to trace.)

**Comment by k4lizen** [comment]
@jnwilson did you figure this out?

**Comment by hachinijuku** [comment]
I can't recall exactly what happened 3 years ago, but I think this is the relevant solution:

https://github.com/frida/frida/issues/2384

**Comment by k4lizen** [comment]
ah yeah, I figured it out, but thanks, don't know how I missed that issue
